name: Deploy to GitHub Pages

on:
  schedule:
    - cron: '*/30 * * * *'  # 每30分钟运行一次
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install Dependencies
        run: |
          echo "安装项目依赖..."
          npm install
          echo "安装完成"
          
      - name: Create Directories
        run: |
          mkdir -p data
          mkdir -p public
          
      - name: Fetch Data from Feishu
        env:
          VITE_APP_ID: ${{ secrets.VITE_APP_ID }}
          VITE_APP_SECRET: ${{ secrets.VITE_APP_SECRET }}
          VITE_BASE_ID: ${{ secrets.VITE_BASE_ID }}
          VITE_TABLE_ID: ${{ secrets.VITE_TABLE_ID }}
        run: |
          echo "检查环境变量是否设置..."
          if [ -z "$VITE_APP_ID" ]; then
            echo "错误: VITE_APP_ID 未设置"
            exit 1
          fi
          if [ -z "$VITE_APP_SECRET" ]; then
            echo "错误: VITE_APP_SECRET 未设置"
            exit 1
          fi
          if [ -z "$VITE_BASE_ID" ]; then
            echo "错误: VITE_BASE_ID 未设置"
            exit 1
          fi
          if [ -z "$VITE_TABLE_ID" ]; then
            echo "错误: VITE_TABLE_ID 未设置"
            exit 1
          fi
          echo "所有环境变量已正确设置"
          echo "开始获取数据..."
          node scripts/fetch-data.js
          
      - name: Check Data Files
        run: |
          echo "检查数据文件..."
          if [ ! -f "data/raw.json" ]; then
            echo "错误: raw.json 不存在"
            exit 1
          fi
          if [ ! -f "data/stats.json" ]; then
            echo "错误: stats.json 不存在"
            exit 1
          fi
          echo "数据文件检查通过"
          echo "raw.json 内容预览:"
          head -n 20 data/raw.json
          echo "stats.json 内容:"
          cat data/stats.json

      - name: Copy Data Files to Public Directory
        run: |
          echo "复制数据文件到 public 目录..."
          cp -r data public/
          echo "public 目录内容:"
          ls -la public/
          echo "public/data 目录内容:"
          ls -la public/data/

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Build with Vite
        run: |
          echo "开始构建..."
          npm run build
          echo "构建完成，检查 dist 目录:"
          ls -la dist/
          echo "检查 dist/data 目录:"
          ls -la dist/data/
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
