name: Deploy to GitHub Pages

on:
  schedule:
    - cron: '*/30 * * * *'  # 每30分钟运行一次
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install Dependencies
        run: npm install
          
      - name: Create Data Directory
        run: mkdir -p data
        
      - name: Fetch Data from Feishu
        env:
          VITE_APP_ID: ${{ secrets.VITE_APP_ID }}
          VITE_APP_SECRET: ${{ secrets.VITE_APP_SECRET }}
          VITE_BASE_ID: ${{ secrets.VITE_BASE_ID }}
          VITE_TABLE_ID: ${{ secrets.VITE_TABLE_ID }}
        run: |
          node scripts/fetch-data.js
          
      - name: Build
        env:
          VITE_APP_ID: ${{ secrets.VITE_APP_ID }}
          VITE_APP_SECRET: ${{ secrets.VITE_APP_SECRET }}
          VITE_BASE_ID: ${{ secrets.VITE_BASE_ID }}
          VITE_TABLE_ID: ${{ secrets.VITE_TABLE_ID }}
        run: npm run build
        
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages
          clean: true
